#!/bin/bash

show_usage_and_exit() {
    echo -e "$2\\n"
    echo -e "Usage: $0 <command> <args>"
    echo -e "Commands: help, install, uninstall, update, add-plugin, remove-plugin, update-plugins\\n"
    echo -e "  * help - show this message"
    echo -e "  * install - [not implmemented] link dotfiles, init plugin submodules"
    echo -e "  * uninstall - [not implmemented] unlink dotfiles"
    echo -e "  * update - pull latest master and update plugins"
    echo -e "  * add-vim-plugin <http-url-to-github> - add new plugin submodule"
    echo -e "  * remove-vim-plugin <name-in-bundle-folder> - remove plugin submodule"
    echo -e "  * update-submodules - init/update plugin submodules"
    echo -e "  * update - pull latest master and update all submodules"
    echo -e "\\n"
    exit "$1"
}

install() {
    echo "Not implemented"
    exit 1
}

update() {
    echo -e "Pulling master..."
    git pull origin master
    update_submodules
    echo -e "Done updating"
}

add_vim_plugin() {
    echo "Adding plugin $1..."
    cd vim/bundle
    git submodule add "$1"
    echo "Plugin $1 succesfully added"
    echo "Don't forget to update WHATS_INSIDE.md!"
}

remove_vim_plugin() {
    echo "Removing_plugin $1..."
    git submodule deinit -f -- "vim/bundle/$1"
    rm -rf ".git/modules/vim/bundle/$1"
    git rm -f "vim/bundle/$1"
    echo "Plugin $1 successfully removed"
}

update_submodules() {
    echo -e "Updating submodules..."
    cd bundle
    git submodule init
    git submodule update
    echo -e "Done updating submodules"
}


set -e

basedir=$(dirname "$0")
cd "$basedir/.." || exit 2

if [ -z "$1" ]; then
    show_usage_and_exit 1 "Command is not specified"
fi

command="$1"
shift

case $command in
    "help")
        show_usage_and_exit 0
        ;;
    "install")
        install
        ;;
    "uninstall")
        install
        ;;
    "update")
        update
        ;;
    "add-vim-plugin")
        if [ -z "$1" ]; then
            show_usage_and_exit 2 "Please specify valid github url (preferrably http)"
        fi
        add_vim_plugin "$1"
        ;;
    "remove-vim-plugin")
        if [ -z "$1" ]; then
            show_usage_and_exit 3 "Please specify plugin name"
        fi
        remove_vim_plugin "$1"
        ;;
    "update-submodules")
        update_submodules
        ;;
esac
