#!/usr/bin/env zsh

usage() {
    echo "Usage: $1 entity [sub-entity]"
    echo "  entity: folder"
    echo "  entity: file, sub-entity: line"
}

if [ -z "$1" ]; then
    usage "$0"
    exit 1
fi


if [ -d "$1" ]; then
    # folder
    ls -ahH --group-directories-first --color "$1"
elif [ -f "$1" ]; then
    # file and line
    if [ -n "$2" ]; then
        if [ -x "$(command -v bat)" ]; then
            bat --color=always --style=plain "$1" --highlight-line "$2"
        else
            vimfzf_preview_bin="$(dirname $0)/../vim/pack/2-bundle/start/fzf.vim/bin/preview.sh"
            "$vimfzf_preview_bin" "$1:$2"
        fi
    else
        # just file
        if [ -x "$(command -v bat)" ]; then
            bat --color=always --style=plain "$1"
        else
            cat "$1"
        fi
    fi
fi
